---
# Default joystick config for an XBOX Series X/S Controller

joy_node:
  ros__parameters:
    device_id: 0  # ID connection /dev
    deadzone: 0.05  # Joystick deadzone
    autorepeat_rate: 20.0  # Repeat action rate

teleop_twist_joy_node:
  ros__parameters:
    # Linear movement (direction of X axis)
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    # Angular movement (around Z axis)
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    # enable_button: 2
    # enable_turbo_button: 5
    # require_enable_button: true
